#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: ybinst-firstinstance-initial-admin 
  namespace: #@ data.values.namespace
type: Opaque
stringData:
  username: ybdadmin
  password: foobar